version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200   # HTTP API
      - 9600:9600   # Monitoring (необязательно)
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data:
