services:
  config_watcher:
      build:
        context: ../services/config_watcher
        dockerfile: Dockerfile
      volumes:
        - ../config:/app/config
        - ../utils:/app/utils
      restart: unless-stopped
      networks:
      - bot_network

networks:
  bot_network:
    external: true
    name: docker_bot_network