services:
  config_server:
    build:
      context: ../services/config_server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../services/config_server:/app
      - ../services/config_server/node_modules:/app/node_modules
      - ../config:/app/config
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    external: true
    name: docker_bot_network
