services:
  log_writer_service:
    build:
      context: ../services/logging
      dockerfile: Dockerfile
    container_name: log_writer_service
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../services/logging:/app
      - ../services/logging/node_modules:/app/node_modules
    networks:
      - bot_network

networks:
  bot_network:
    external: true
    name: docker_bot_network