services:
  config_server:
    build:
      context: ../services/config_server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../config:/app/config
      - ../utils:/app/utils
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    external: true
    name: docker_bot_network
