services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: solana
      POSTGRES_PASSWORD: solana
      POSTGRES_DB: solana_bot
    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - bot_network

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=4e4et04kA!+QhyD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - bot_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - opensearch
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LIVE_ENABLED=false            # <--- отключает live-функции
    volumes:
      - ../services/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../services/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../services/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - bot_network

  fluent-bit:
    image: fluent/fluent-bit:3.0.4
    container_name: fluent-bit
    restart: unless-stopped
    depends_on:
      - opensearch
    volumes:
      - ../services/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ../services/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ../logs:/logs:ro
      - fluentbit-buffer:/fluent-bit/buffer
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    networks:
      - bot_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540" 
    networks:
      - bot_network
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis


networks:
  bot_network:
    driver: bridge

volumes:
  redis-data:
    external: true
  pg_data:
    external: true
  opensearch-data:
    external: true
  fluentbit-buffer:
    external: true
  redisinsight-data:
    external: true
