version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bot_network

  solana_subscriber:
    build: ../services/solana_subscriber
    container_name: solana_subscriber
    restart: always
    env_file:
      - ../config/.env
    volumes:
      - ../utils:/app/utils  # 📌 Подключаем `utils` из основного каталога
    depends_on:
      redis:
        condition: service_started
    networks:
      - bot_network
    healthcheck:  # 📌 Добавляем проверку здоровья контейнера
      test: ["CMD", "node", "-e", "console.log('Healthcheck OK')"]
      interval: 10s
      timeout: 5s
      retries: 5

  account_manager:
    build: ../services/account_manager
    container_name: account_manager
    restart: always
    env_file:
      - ../config/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started
      solana_subscriber:
        condition: service_healthy
    networks:
      - bot_network
    healthcheck:  # 📌 Добавляем healthcheck
      test: ["CMD", "node", "-e", "console.log('Healthcheck OK')"]
      interval: 10s
      timeout: 5s
      retries: 5

  log_processor:
    build: ../services/log_processor
    container_name: log_processor
    restart: always
    env_file:
      - ../config/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started
      solana_subscriber:
        condition: service_healthy
      account_manager:
        condition: service_healthy
    networks:
      - bot_network

  config_server:
    build:
      context: ./services/config_server
    ports:
      - "3001:3001"
    volumes:
      - ./config:/app/config        # монтируем config.json
    environment:
      - NODE_ENV=production

  ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - config_server

networks:
  bot_network:
    driver: bridge
